// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIeAdVU98dkVWfaraxTELOMJiM2OegCF0',
    appId: '1:833396759189:web:1e1db1f412ff390ddb199c',
    messagingSenderId: '833396759189',
    projectId: 'chat-app-b6286',
    authDomain: 'chat-app-b6286.firebaseapp.com',
    storageBucket: 'chat-app-b6286.appspot.com',
    measurementId: 'G-Y3VQCQ0EKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCifXqOfdiZrbWrze_gA8JwGfHZVB55Yjk',
    appId: '1:833396759189:android:49aefd50f896ca19db199c',
    messagingSenderId: '833396759189',
    projectId: 'chat-app-b6286',
    storageBucket: 'chat-app-b6286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0SjWQlL31WEBZwJME2LrBiUkUXn_ca_g',
    appId: '1:833396759189:ios:56d6a1459778c0ebdb199c',
    messagingSenderId: '833396759189',
    projectId: 'chat-app-b6286',
    storageBucket: 'chat-app-b6286.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0SjWQlL31WEBZwJME2LrBiUkUXn_ca_g',
    appId: '1:833396759189:ios:0b23d0033dc2ae53db199c',
    messagingSenderId: '833396759189',
    projectId: 'chat-app-b6286',
    storageBucket: 'chat-app-b6286.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
